#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

GHSI_PATH=$SCRIPT_DIR/venv/bin/gh-sync-issues

PYTHON=$(which python3 || which python)

if [ ! -f $GHSI_PATH ]
then
    echo "Installing extension dependencies..."
    cd $SCRIPT_DIR
    eval $PYTHON -m venv venv || { echo "Could not create embedded virtualenv" ; exit 1; }
    source ./venv/bin/activate || { echo "Failed to activate embedded virtualenv" ; exit 1; }
    pip install . > /dev/null || { echo "Failed to install package." ; exit 1; }
    echo "Successful. You shouldn't see this message again."
fi

# Run the actual script
if [ -f $GHSI_PATH ]
then
    exec $GHSI_PATH "$@"
else
    echo "Could not find Python script ${GHSI_PATH}"
fi


